"""create mahasiswa table

Revision ID: 7d4b45b2ac58
Revises: 
Create Date: 2025-05-16 17:02:41.877104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d4b45b2ac58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mahasiswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nim', sa.Text(), nullable=False),
    sa.Column('nama', sa.Text(), nullable=False),
    sa.Column('jurusan', sa.Text(), nullable=False),
    sa.Column('tanggal_lahir', sa.Date(), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mahasiswa')),
    sa.UniqueConstraint('nim', name=op.f('uq_mahasiswa_nim'))
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models'))
    )
    op.create_index('my_index', 'models', ['name'], unique=True, mysql_length=255)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('my_index', table_name='models', mysql_length=255)
    op.drop_table('models')
    op.drop_table('mahasiswa')
    # ### end Alembic commands ###
